### ISSUE TITLE
QUESTION & SUGGESTION

### ISSUE THREAD

**Issue by Johnsonk79** [notacoderr/EntityLifeSpan#1]
Hi! Does an arrow that has been shot work with this plugin? Also, can you please add an option in config for all items instead of putting the item's name 1 by 1? Thanks a lot!

**Comment by notacoderr** [comment]
Thanks, 

first, it currently removes ItemEntity classes (which are items that were dropped on the world). but I can add Arrow if you want.

second, sure i can do that!

**Comment by Johnsonk79** [comment]
That would be awesome, I would really appreciate it! Thanks a lot! :D
